package model

import "os"

var AUTH_SECRET = os.Getenv("AUTH_SECRET")
var AUTH_EXPIRATION = os.Getenv("AUTH_EXPIRATION")
var WEBAPP_ADDRESS = os.Getenv("WEBAPP_ADDRESS")
var ACTIVATION_SECRET_KEY = os.Getenv("ACTIVATION_SECRET_KEY")
var ACTIVATION_SECURITY_PASSWORD_SALT = os.Getenv("ACTIVATION_SECURITY_PASSWORD_SALT")
var STRIPE_API_SECRET_KEY = os.Getenv("STRIPE_API_SECRET_KEY")
var STRIPE_EVENT_PAYMENT_WEBHOOK_SECRET = os.Getenv("STRIPE_EVENT_PAYMENT_WEBHOOK_SECRET")
var OPENSEA_API_KEY = os.Getenv("OPENSEA_API_KEY")
